"""Initial migration.

Revision ID: 07125fc402cd
Revises: 
Create Date: 2024-05-19 11:32:27.527577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07125fc402cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
